/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Alessandro
 * Created: 19-mag-2016
 */
CREATE TABLE professore
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(128),
    cognome VARCHAR(128),
    username VARCHAR(128),
    password VARCHAR(32),
    orario_ricevimento VARCHAR(128)
);

CREATE TABLE studente
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(128),
    cognome VARCHAR(128),
    username VARCHAR(128),
    password VARCHAR(32),
    matricola VARCHAR(5)
);

CREATE TABLE materia
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(128)
);

CREATE TABLE esami_superati
(
    idMateria INTEGER,
    FOREIGN KEY (idMateria) REFERENCES materia(id),
    idStudente INTEGER,
    FOREIGN KEY (idStudente) REFERENCES studente(id),
    PRIMARY KEY (idMateria, idStudente),
    voto INTEGER,
    descrizione LONG VARCHAR 
);

CREATE TABLE materie_assegnate
(
    idMateria INTEGER,
    FOREIGN KEY (idMateria) REFERENCES materia(id),
    idProfessore INTEGER,
    FOREIGN KEY (idProfessore) REFERENCES professore(id),
    PRIMARY KEY (idMateria, idProfessore)
);

CREATE TABLE pianodistudi
(
    idMateria INTEGER,
    FOREIGN KEY (idMateria) REFERENCES materia(id),
    idStudente INTEGER,
    FOREIGN KEY (idStudente) REFERENCES studente(id),
    PRIMARY KEY (idMateria, idStudente)
);

INSERT INTO professore(id, nome, cognome, username, password)
VALUES (default, 'Davide', 'Spano', 'SpanoDavide', '0'),
(default, 'Riccardo', 'Scateni', 'ScateniRiccardo', '1'),
(default, 'Gianni', 'Fenu', 'DjannyFenu', '2');

INSERT INTO studente(id, nome, cognome, username, password)
VALUES (default, 'Alessandro', 'Carcangiu', 'CarcangiuAlessandro', '0'),
(default, 'Gianmarco', 'Cherchi', 'CherchiGianmarco', '1'),
(default, 'LaTorre', 'MarÃ²', 'LaTorreMarÃ²', '2');

INSERT INTO materia(id, nome)
VALUES (default, 'AMM'),
(default, 'IUM'),
(default, 'PR1'),
(default, 'RETI'),
(default, 'PSI');

INSERT INTO esami_superati(idMateria, idStudente, voto, descrizione)
VALUES (1, 1, 30, ''),
(2, 1, 30, ''),
(1, 2, 30, ''),
(3, 2, 30, ''),
(5, 3, 18, '');

INSERT INTO materie_assegnate(idMateria, idProfessore)
VALUES (1,1),
(2,1),
(3,2),
(4,3),
(5,3);

INSERT INTO pianodistudi(idMateria, idStudente)
VALUES (3, 1),
(4, 1),
(5, 1),
(2, 2),
(3, 2),
(4, 2),
(5, 2),
(1, 3),
(2, 3),
(3, 3),
(4, 3);
